### ISSUE TITLE
No data after cloning the repo. 

### ISSUE THREAD

**Issue by abhijith-athreya** [AbhilashaRavichander/PrivacyQA_EMNLP#1]
[PrivacyQA_EMNLP-master.zip](https://github.com/AbhilashaRavichander/PrivacyQA_EMNLP/files/4109839/PrivacyQA_EMNLP-master.zip)

The files don't have any content after cloning or downloading. Attaching the zip file downloaded from the repo.

**Comment by AbhilashaRavichander** [comment]
This is a known issue with GIT LFS. Cloning the repo and running 

```
git lfs fetch
git lfs pull
```

 should work to retrieve the data. Let me know if it doesn't!
