### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by rizwan09** [AbhilashaRavichander/PrivacyQA_EMNLP#3]
Hi,
I am interested in your research and currently trying to improve the QA performance. Although I read the paper but still I have two following clarification questions. Would you please clarify them. 

1) Test dataset has multiple annotators. So how do you take the gold relevant label. If any of them says it's relevant (i.e., the any_relevant label) or  what the majority says etc., ?

2) How do we take the unanswerability label? So if the annotators did not find any relevance evidence for all the questions w.r.t a policy doc then you say the policy doc is unanswerable? Or what?

Thanks,

**Comment by AbhilashaRavichander** [comment]
Hi, sorry for the late response! I somehow missed this.

1) For the evaluation, we didn't do a majority vote. For each classifier output,  given n reference answers, we report the average of the maximum F1 computed from each n − 1 subset with respect to the heldout reference. Answers are in the form of a set of relevant sentences from a policy.  This is explained in the evaluation section on Page 7 in the arxiv draft. Let me know if you need further clarification.

2) Yes, I believe if no annotator found a relevant segment we say the question is unanswerable.
